version: "3.8"

services:
    matrix-line:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                COMMIT: "${COMMIT:-unknown}"
                BUILD_TIME: "${BUILD_TIME:-unknown}"
                MAUTRIX_VERSION: "${MAUTRIX_VERSION:-unknown}"
        volumes:
            - ./data:/data
        restart: unless-stopped
